# Generated by Django 2.1.5 on 2019-02-09 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 14, 9, 9, 796369, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
