# Generated by Django 2.1.5 on 2019-02-09 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20190209_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 14, 20, 2, 584622, tzinfo=utc)),
        ),
    ]
