# Generated by Django 2.1.5 on 2019-02-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_catgeory'),
        ('blogapp', '0007_auto_20190213_0739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catgeory',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_name',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Catgeory'),
        ),
    ]
