# Generated by Django 2.1.5 on 2019-02-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20190213_0941'),
        ('user', '0004_catgeory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgeory',
            new_name='Catgeories',
        ),
        migrations.AlterModelTable(
            name='catgeories',
            table='categories',
        ),
    ]
